# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

branches:
  only:
    - master

install:
  # Install the latest stable of the nodejs version
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Nodejs projects don't "build"
build: off