name: Continous Integration
on: [push, pull_request]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} os ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12, 13]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test